version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=6379
    depends_on:
      - db

  db:
    image: redis:latest
    ports:
      - "6379:6379"
